FROM openjdk
WORKDIR /usr/src
COPY ./target/NewsAppBookmarks-0.0.1-SNAPSHOT.jar NewsAppBookmarks-0.0.1-SNAPSHOT.jar
#EXPOSE 8083
ENTRYPOINT ["java","-jar","/usr/src/NewsAppBookmarks-0.0.1-SNAPSHOT.jar"] 