FROM openjdk
WORKDIR /usr/src
COPY ./target/NewsAppFavorite-0.0.1-SNAPSHOT.jar NewsAppFavorite-0.0.1-SNAPSHOT.jar
#EXPOSE 8082
ENTRYPOINT ["java","-jar","/usr/src/NewsAppFavorite-0.0.1-SNAPSHOT.jar"] 